# Copyright (c) 2019-2024 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

dependencies:
  # HPA Metrics
  - name: metrics-server
    version: 3.12.1
    condition: metrics-server.enabled
    repository: https://kubernetes-sigs.github.io/metrics-server
  # Ingress Controller
  - name: ingress-nginx
    version: 4.12.0
    condition: ingress-nginx.enabled
    repository: https://kubernetes.github.io/ingress-nginx
