## https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/README.md
## https://artifacthub.io/packages/helm/metrics-server/metrics-server
metrics-server:
  enabled: true
  args: [
    # not recommended in production
    --kubelet-insecure-tls,
    --kubelet-preferred-address-types=InternalIP
  ]

# https://kubernetes.github.io/ingress-nginx/
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
ingress-nginx:
  enabled: true
  controller:
    metrics:
      enabled: true
    ingressClassResource:
      default: true

# https://github.com/jetstack/cert-manager/blob/master/README.md
# https://artifacthub.io/packages/helm/jetstack/cert-manager
cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false

