apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: inst-apm-java
  namespace: mushop
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: container-registry.oracle.com/oci_observability_management/oci-apm-java-agent
    env:
      # - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      #   value: <your-data-upload-endpoint>/20200101/opentelemetry/private/v1/traces
      # - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
      #   value: http/protobuf
      # - name: OTEL_EXPORTER_OTLP_HEADERS
      #   value: Authorization=dataKey <your-private-data-key>
      # - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
      #   value: Authorization=dataKey <your-private-data-key>
      # - name: OTEL_METRICS_EXPORTER
      #   value: none
      # - name: OTEL_LOGS_EXPORTER
      #   value: none
      - name: OTEL_com_oracle_apm_agent_data_upload_endpoint
        value: <your-data-upload-endpoint>
      - name: OTEL_com_oracle_apm_agent_private_data_key
        value: <your-private-data-key>
      - name: OTEL_com_oracle_apm_agent_config_trace_jvmargs_createChildSpans
        value: "false"
      - name: OTEL_com_oracle_apm_agent_config_trace_jvmargs_createSpan
        value: "false"
        
        