replicaCount: 1

image:
  repository: sjc.ocir.io/orasejapan/mushop-fulfillment
  tag: ${VERSION}
  pullPolicy: Always

osb: {}

env:
  newOrdersSubject: mushop-orders
  shippedOrdersSubject: mushop-shipments
  simulationDelay: 10000

service:
  port: 80

streaming:
  secret: kafka-secret
  serverKey: server
  configKey: config

opentelemetry:
  provider: oci