replicaCount: 1

image:
  repository: nrt.ocir.io/orasejapan/mushop-fulfillment
  tag: latest
  pullPolicy: Always

osb: {}

env:
  newOrdersSubject: mushop-orders
  shippedOrdersSubject: mushop-shipments
  simulationDelay: 10000

service:
  port: 80

opentelemetry:
  provider: oci
  oci:
    secret: apm-secret
    endpoint: endpoint
    key: credentials
  otel:
    secret: otel-secret
    endpoint: 
    oltp:
      headers:
      traceHeaders:
