title: mushop
description: This is a RMS stack for OCI Cloud Native Book!
schemaVersion: 1.1.0
version: "20190304"

locale: "ja"

variableGroups:
  - title: "Terraform Provider Variables"
    variables:
      - ${region}
      - ${tenancy_ocid}
      - ${current_user_ocid}
      - ${compartment_ocid}
  - title: "Email Delivery"
    variables:
      - ${email_address}
  - title: "OCI Vault and Secrets"
    variables:
      - ${oci_registry_username}
      - ${oci_registry_password}

variables:
  # Terraform Provider Variables
  region:
    type: oci:identity:region:name
    required: true
    description: Enter your region
  tenancy_ocid:
    type: string
    required: true
    description: Enter your Tenancy OCID(Inherit from OCI Console)
  current_user_ocid:
    type: string
    required: true
    description: Enter your User OCID(Inherit from OCI Console)
  compartment_ocid:
    type: string
    required: true
    description: Enter your Compartment OCID(Inherit from OCI Console)
  # Email Delivery
  email_address:
    type: string
    required: true
    description: Enter your email address
    pattern: ^[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
  # OCI Vault and Secrets
  oci_registry_username:
    type: string
    required: true
    description: Enter your registry username
  oci_registry_password:
    type: password
    required: true
    description: Enter your registry password
