apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders.fullname" . }}
  labels: {{ include "orders.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "orders.name" . }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "orders.name" . }}
        mockmode: {{ .Values.global.mock.service | quote }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "80"
        {{ if eq .Values.opentelemetry.provider "oci" }}
          instrumentation.opentelemetry.io/inject-java: "mushop/inst-apm-java"
        {{ else }}
          instrumentation.opentelemetry.io/inject-java: "true"
        {{ end }}
    spec:
      initContainers:
        {{- include "orders.init.wallet" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: http

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-compati-secret
                  key: server
            - name: KAFKA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-compati-secret
                  key: sasl-jaas-config
            {{ if eq .Values.opentelemetry.provider "oci" }}
              - name: OTEL_com_oracle_apm_agent_private_data_key
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.secret }}"
                    key: "{{ .Values.opentelemetry.endpoint }}"
              - name: OTEL_com_oracle_apm_agent_data_upload_endpoint
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.secret }}"
                    key: "{{ .Values.opentelemetry.key }}"
            {{ else }}
              - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.otel.secret }}"
                    key: "{{ .Values.opentelemetry.otel.endpoint }}"
              - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
                value: http/protobuf
              - name: OTEL_EXPORTER_OTLP_HEADERS
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.otel.secret }}"
                    key: "{{ .Values.opentelemetry.otel.oltp.headers }}"
              - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.otel.secret }}"
                    key: "{{ .Values.opentelemetry.otel.oltp.traceHeaders }}"
            - name: ORDERS_NEW
              value: "{{ .Values.env.newOrdersSubject }}"
            - name: ORDERS_SHIPPED
              value: "{{ .Values.env.shippedOrdersSubject }}"
            - name: ZIPKIN
              value: {{ .Values.env.zipkin }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts }}
            - name: NATS_HOST
              value: "{{ .Release.Name }}-{{ .Values.env.natsHost }}"
            - name: NATS_PORT
              value: "{{ .Values.env.natsPort }}"
            {{- include "orders.oadb.connection" . | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            {{- include "orders.mount.wallet" . | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        {{- include "orders.volumes" . | nindent 8 }}
      nodeSelector:
          kubernetes.io/os: linux
