micronaut:
  application:
    name: fulfillment-service
  scan:
    packages: 'mushop' 
  server:
    port: 80
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    binders:
      jvm:
        enabled: true
      web:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true

endpoints:
    prometheus:
        enabled: true
        sensitive: false
        
mushop:
  messaging:
    simulation-delay: ${simulation.delay:8000}
    subjects:
      orders: mushop-orders
      shipments: mushop-shipments
