global:
  mock:
    service: "false"
  osb:
    instanceName: mushop
  ociAuthSecret: oci-credentials
  oadbAdminSecret: oadb-admin
  oadbWalletSecret: oadb-wallet
  oadbConnectionSecret: oadb-connection
  oosBucketSecret: oos-bucket
  okeVirtualNodesSupport: false

# Depending on the scenario, certain resources might need to be skipped.
# For example, --set tags.streaming=false to disable required streaming manifests
tags:
  streaming: true
  atp: true

ingress:
  enabled: true
  tls: false

api:
  enabled: true
  image:
    repository: ocir.${REGION}.oci.oraclecloud.com/${NAMESPACE}/mushop-api
    tag: ${VERSION}
    pullPolicy: Always
  cache:
    secret: cache-endpoint
    hostKey: host
  env:
    mediaUrl: ${PAR}
    newsletterSubscribeUrl: https://${APIGATEWAY}/newsletter/subscribe

assets:
  enabled: true

carts:
  enabled: true
  image:
    repository: ocir.${REGION}.oci.oraclecloud.com/${NAMESPACE}/mushop-carts
    tag: ${VERSION}
    pullPolicy: Always
  opentelemetry:
    provider: oci

catalogue:
  enabled: true

edge:
  enabled: true

orders:
  enabled: true
  image:
    repository: ocir.${REGION}.oci.oraclecloud.com/${NAMESPACE}/mushop-orders
    tag: ${VERSION}
    pullPolicy: Always
  streaming:
    secret: kafka-secret
    serverKey: server
    configKey: config
  opentelemetry:
    provider: oci

payment:
  enabled: true

storefront:
  enabled: true
  image:
    repository: ocir.${REGION}.oci.oraclecloud.com/${NAMESPACE}/mushop-storefront
    tag: ${VERSION}
    pullPolicy: Always

fulfillment:
  enabled: true
  image:
    repository: ocir.${REGION}.oci.oraclecloud.com/${NAMESPACE}/mushop-fulfillment
    tag: ${VERSION}
    pullPolicy: Always
  streaming:
    secret: kafka-secret
    serverKey: server
    configKey: config
  opentelemetry:
    provider: oci

user:
  enabled: true
