global:
  mock:
    service: "false"
  osb:
    instanceName: mushop
  ociAuthSecret: oci-credentials
  oadbAdminSecret: oadb-admin
  oadbWalletSecret: oadb-wallet
  oadbConnectionSecret: oadb-connection
  oosBucketSecret: oos-bucket
  okeVirtualNodesSupport: false

# Depending on the scenario, certain resources might need to be skipped.
# For example, --set tags.streaming=false to disable required streaming manifests
tags:
  streaming: true
  atp: true

ingress:
  enabled: true
  tls: false

api:
  enabled: true
  env:
    mediaUrl:                 # Object Storage URL for catalogue image assets
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)

assets:
  enabled: true

carts:
  enabled: true

catalogue:
  enabled: true

edge:
  enabled: true

orders:
  enabled: true

payment:
  enabled: true

storefront:
  enabled: true

fulfillment:
  enabled: true

user:
  enabled: true

opentelemetry:
  provider: oci