apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carts.fullname" . }}
  labels: {{ include "carts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "carts.name" . }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "carts.name" . }}
        mockmode: {{ .Values.global.mock.service | quote }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        {{ if eq .Values.opentelemetry.provider "oci" }}
          instrumentation.opentelemetry.io/inject-java: "mushop/inst-apm-java"
        {{ else }}
          instrumentation.opentelemetry.io/inject-java: "true"
        {{ end }}
    spec:
      initContainers:
        {{- include "carts.init.wallet" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ZIPKIN
              value: {{ .Values.env.zipkin }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts }}
            {{- include "carts.oadb.connection" . | nindent 12 }}
            {{ if eq .Values.opentelemetry.provider "oci" }}
              - name: OTEL_com_oracle_apm_agent_private_data_key
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.secret }}"
                    key: "{{ .Values.opentelemetry.endpoint }}"
              - name: OTEL_com_oracle_apm_agent_data_upload_endpoint
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.secret }}"
                    key: "{{ .Values.opentelemetry.key }}"
            {{ else }}
              - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.otel.secret }}"
                    key: "{{ .Values.opentelemetry.otel.endpoint }}"
              - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
                value: http/protobuf
              - name: OTEL_EXPORTER_OTLP_HEADERS
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.otel.secret }}"
                    key: "{{ .Values.opentelemetry.otel.oltp.headers }}"
              - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Values.opentelemetry.otel.secret }}"
                    key: "{{ .Values.opentelemetry.otel.oltp.traceHeaders }}"
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            {{- include "carts.mount.wallet" . | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        {{- include "carts.volumes" . | nindent 8 }}
      nodeSelector:
          kubernetes.io/os: linux
