apiVersion: v1
kind: Service
metadata:
  name: {{ include "carts.fullname" . }}
  labels:
{{ include "carts.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "carts.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: 80
