---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushop-api
  labels:
    name: api
    app.kubernetes.io/name: api
    layer: client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        name: api
        layer: client
        app.kubernetes.io/name: api
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: api
        image: "nrt.ocir.io/orasejapan/mushop-api"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: SESSION_REDIS
          value: aaassl65iqa5zdxhoid2th6rgncjiawkpkrcrm4ets2qwlj22rviz3a-p.redis.uk-london-1.oci.oraclecloud.com
        - name: CATALOGUE_URL
          value: http://mushop-catalogue
        - name: ORDERS_URL
          value: http://mushop-orders
        - name: CARTS_URL
          value: http://mushop-carts
        - name: USERS_URL
          value: http://mushop-user
        - name: EVENTS_URL
          value: http://mushop-events
        - name: STATIC_MEDIA_URL
          value: /assets
        - name: NEWSLETTER_SUBSCRIBE_URL
          value: ""
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
            drop:
              - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
