---
# Source: mushop/charts/fulfillment/templates/fulfillment-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushop-fulfillment
  labels:
    app.kubernetes.io/name: fulfillment
    helm.sh/chart: fulfillment-0.1.0
    app.kubernetes.io/instance: mushop
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    run: fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfillment
      app.kubernetes.io/name: fulfillment
      run: fulfillment
  template:
    metadata:
      labels:
        app: fulfillment
        version: "1.1.0"
        app.kubernetes.io/name: fulfillment
        run: fulfillment
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /prometheus
        prometheus.io/port: "80"
        instrumentation.opentelemetry.io/inject-java: "mushop/inst-apm-java"
        #instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: fulfillment
          #image: "iad.ocir.io/oracle/ateam/mushop-fulfillment:1.1.0"
          image: "nrt.ocir.io/orasejapan/mushop-fulfillment"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-compati-secret
                  key: server
            - name: KAFKA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-compati-secret
                  key: sasl-jaas-config
            - name: ORDERS_NEW
              value: "mushop-orders"
            - name: ORDERS_SHIPPED
              value: "mushop-shipments"
            - name: SIMULATION_DELAY
              value: "10000"
